version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dvhs-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dvhs
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dvhs_local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
